# Generated by Django 3.2.5 on 2021-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Посилання на латиниці. Приклад: zno-na-200', unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Опис')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
    ]
