# Generated by Django 3.2.5 on 2021-07-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
    ]
