# Generated by Django 3.2.5 on 2021-07-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('slug', models.SlugField(help_text='Посилання на латиниці. Приклад: imya-familiya', unique=True, verbose_name='Слаг')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('bio', models.TextField(verbose_name='Біографія')),
                ('avatar', models.ImageField(upload_to='teachers/', verbose_name='Фото')),
            ],
        ),
    ]
