# Generated by Django 3.2.5 on 2021-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Викладач', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(help_text='У форматі +380 (хх) ххх-хх-хх', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
