# Generated by Django 3.2.5 on 2021-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210708_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='summary',
            field=models.TextField(default='def', max_length=400, verbose_name='Коротко про викладача'),
            preserve_default=False,
        ),
    ]
