# Generated by Django 3.2.5 on 2021-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(blank=True, help_text='Логін без @. Наприклад tekhnar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.CharField(blank=True, help_text='Логін без @. Наприклад tekhnar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram',
            field=models.CharField(blank=True, help_text='Логін без @. Наприклад tekhnar', max_length=50, null=True),
        ),
    ]
