# Generated by Django 3.2.5 on 2021-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20210708_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.AddField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(default='Васильович', max_length=50, verbose_name='По батькові'),
            preserve_default=False,
        ),
    ]
