# Generated by Django 3.2.5 on 2021-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_auto_20210702_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('slug', models.SlugField(help_text='Посилання на латиниці. Приклад: matematika-zno-2021', unique=True, verbose_name='Слаг')),
                ('picture', models.ImageField(upload_to='courses/', verbose_name='Обкладинка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублікувати')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Час редагування')),
                ('teacher', models.ManyToManyField(help_text='Виберіть одного або декілька викладачів', to='teachers.Teacher', verbose_name='Викладачі')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
            },
        ),
    ]
