# Generated by Django 3.2.5 on 2021-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='default', max_length=300, verbose_name='Короткий Опис'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='default', max_length=50, verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.SmallIntegerField(default=2021, verbose_name='Рік'),
            preserve_default=False,
        ),
    ]
