# Generated by Django 3.2.5 on 2021-07-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210702_0753'),
        ('courses', '0003_auto_20210707_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Викладач'),
            preserve_default=False,
        ),
    ]
