# Generated by Django 3.2.5 on 2021-07-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210708_0827'),
        ('courses', '0004_auto_20210707_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teachers.teacher', verbose_name='Викладач'),
        ),
    ]
