# Generated by Django 3.2.5 on 2021-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AddField(
            model_name='course',
            name='instruction',
            field=models.TextField(default='instruction', help_text='Відображається на закритій сторінці всіх уроків курсу', verbose_name='Інструкція'),
            preserve_default=False,
        ),
    ]
