# Generated by Django 3.2.5 on 2021-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на домашнє завдання'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на матеріали'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на трансляцію'),
        ),
    ]
